- src/scss/_common.scss
- src/scss/components/Hero.module.scss
+ Add new partial common.scss
+ Foundation file for future component development
+ Add common to Hero module
> strategy - sass common creation

- src/pages/index.tsx
- src/scss/_extended.scss
- src/scss/extended.scss
- src/scss/main.scss
Default Custom Home Styling – getting closer.
> Home styling

- package-lock.json
- src/pages/[...pageUri].tsx
- src/scss/_extended.scss
Starting to define a simplified page title area with image design.
> Academics title

- src/components/Header.tsx
Fix #63 (minor tweak to get build-step working again)
> address #63

- src/components/BlockRouter.tsx
- src/components/blocks/Card.tsx
- src/scss/_extended.scss
- src/stories/blocks/Card.stories.tsx
Add Card
– Component
– Block Router
– Story
> Reactify card

- src/components/BlockRouter.tsx
- src/components/blocks/CardBody.tsx
- src/stories/blocks/CardBody.stories.tsx
Add Card Body:
– Component
– Router
– Story
> Reactify card body

- src/components/BlockRouter.tsx
- src/components/blocks/CardFooter.tsx
- src/stories/blocks/CardFooter.stories.tsx
Add Card Footer
– Component
– Router
– Story
> Reactify card footer

- src/components/BlockRouter.tsx
- src/components/blocks/CardImage.tsx
- src/stories/blocks/CardImage.stories.tsx
Add Card Image
– Component
– Router
– Story
> Reactify card image

- src/components/BlockRouter.tsx
- src/components/blocks/CardHeading.tsx
- src/stories/blocks/CardHeading.stories.tsx
Add Card Heading
– Component
– Router
– Story
> Reactify card heading

- src/components/BlockRouter.tsx
- src/components/blocks/CardHeader.tsx
- src/stories/blocks/CardHeader.stories.tsx
Add Card Header
– Component
– Router
– Story
> Reactify card header

- src/components/BlockRouter.tsx
- src/components/blocks/CardMain.tsx
- src/stories/blocks/CardMain.stories.tsx
Add Card Main
– Component
– Router
– Story
> Reactify card main

- src/components/BlockRouter.tsx
- src/components/blocks/CardTopcap.tsx
- src/stories/blocks/CardTopcap.stories.tsx
Add Card Topcap
– Component
– Router
– Story
> Reactify card topcap

- src/components/BlockRouter.tsx
- src/components/blocks/Column.tsx
- src/stories/blocks/Column.stories.tsx
Add Column:
– Component
– Router
– Story
> Reactify column

- src/components/BlockRouter.tsx
- src/components/blocks/Columns.tsx
- src/stories/blocks/Columns.stories.tsx
Add Columns
– Component
– Router
– Story
> Reactify columns

- src/components/BlockRouter.tsx
- src/components/blocks/Accordion.tsx
- src/components/blocks/Contact.tsx
- src/components/blocks/Phone.tsx
- src/components/blocks/Phones.tsx
- src/stories/blocks/Phone.stories.tsx
- src/stories/blocks/Phones.stories.tsx
Reactify Phone and Phones blocks, plus some refactoring.
> reactify Phone and Phones blocks, plus some refactor

- src/components/BlockRouter.tsx
- src/components/blocks/Strip.tsx
- src/stories/blocks/Strip.stories.tsx
Reactify strip and basic demo in Storybook
> reactify strip

- src/client/schema.generated.ts
- src/pages/[...pageUri].tsx
- fixes #114
- updates `src/client/schema.generated.ts`
> address #114 (delete stray body tag)

- package-lock.json
- package.json
Address #78 (update React-Bootstrap to version that fixes the bug in question)
> address #78

- src/pages/alpha.tsx
As part of #118, use SSG for the `/alpha` page and refactor it accordingly (to avoid client-side rendering).
Still need to implement search (once the functionality gets ironed out), which will require some refactoring.
> use SSG for alpha-page and refactor accordingly

- package-lock.json
- package.json
- src/components/ParsedMarkup.tsx
- install `html-react-parser`
- make basic `<ParsedMarkup>` component (doesn't do anything yet, and isn't used anywhere yet)
(for #96)
> install html-react-parser, make basic ParsedMarkup component

- public/css/meet.css
Add missing `background-image` style for `.bg-campus` in `meet.css`.
> add background-image to .bg-campus class in meet.css

- src/client/schema.generated.ts
- src/components/Header.tsx
Updates fetchAlert to use https to resolve error
> Updated fetchAlert to use https url

- src/client/schema.generated.ts
- src/pages/[...pageUri].tsx
Fetches page head info from Yoast SEO and adds to page
> Adds head info from Yoast

- src/pages/[...pageUri].tsx
Adds hide page title functionality
> Adds hide page title functionality

- src/pages/alpha.tsx
- src/scss/framework/_custom_variables.scss
- src/scss/framework/styles/_buttons.scss
- src/scss/pages/alpha.module.scss
Changing Layout of page to a 2 column
– reducing alpha size
– stacked on mobile (search first)
Realized sticky letters is not working (in this feature branch or the development branch). Troubleshooting this and working on making the entire search box sticky as well – so it travels down the page with you...
> AZ reduction

- src/scss/_extended.scss
- src/scss/pages/alpha.module.scss
Fix sticky letter and add sticky search box
> Alpha sticky

- src/scss/_extended.scss
- src/scss/framework/components/_cards.scss
- src/scss/framework/components/_columns.scss
- src/scss/framework/styles/_buttons.scss
- src/scss/framework/styles/_frame.scss
- src/scss/framework/styles/_typography.scss
- src/scss/main.scss
visit update and universal styling
– start to migrate patterns in
– fix page intro group
> Cleanup 03

- src/pages/alpha.tsx
- src/scss/pages/alpha.module.scss
– clean up intro section on alpha
– add mobile sticky 
– update font weights and clean up
> Alpha intro

- src/pages/alpha.tsx
- src/scss/pages/alpha.module.scss
– style form / search button
– tweak scale of mobile alphabet
– move request update button to bottom
> Alpha search buttons

- src/pages/404.tsx
> Escapes apostrophe to resolve build error

- src/components/Hero.js
- src/scss/_extended.scss
> Home buttons

- src/components/Header.tsx
- src/scss/framework/regions/_navigation_horizontal.scss
- src/scss/framework/regions/_navigation_megamenu.scss
– made subnav flex with full width children
– change slide in to happen from right 
– prettier formatting
> add flex to sub mobile nav. Change slide in side

- src/components/Header.tsx
> close mobile menu on navigation if needed (#166)

- src/pages/alpha.tsx
Move pound sign to end on `/alpha` page (in both alpha-nav and item-display).
> move pound sign to end on alpha page

- package-lock.json
- package.json
- src/client/schema.generated.ts
- src/components/HomepageVideo.tsx
- src/components/ParsedMarkup.tsx
Get homepage-video working (for #189). Could probably still use some styling tweaks.
> get homepage-video working (#189)

- src/components/UniversalHeader.tsx
- src/scss/framework/regions/_universal-header.scss
– tweak universal nav
– add animation on hover
– visual match to genesis-child
> style universal navigation with hover scale

- src/components/HomepageVideo.tsx
- src/components/ParsedMarkup.tsx
Tweak the homepage-video component (for #189)
- Fix the `<figure>` classes (and refactor ParsedMarkup a bit to clarify what's what)
- Refactor HomepageVideo a bit, including tweaking some styles to improve the layout.
> tweak homepage-video (#189)

- src/scss/framework/components/_cards.scss
- src/scss/framework/components/_columns.scss
- src/scss/framework/components/_list.scss
- src/scss/framework/styles/_blockquote.scss
- src/scss/framework/styles/_typography.scss
– tweak responsive cards for use on outcomes
– tweak blockquote for use on academics
– create new control for breakpoints of columns 40/60
> Punchlist various

- src/scss/framework/regions/_universal-header.scss
- Removed padding from the universal nav to line up items.
> Removing padding to line up mobile navigation.

- src/scss/_extended.scss
- src/scss/framework/components/_cards.scss
- src/scss/framework/styles/_buttons.scss
- src/scss/framework/styles/_patterns.scss
- src/scss/main.scss
– intro spacing fix
– new programCard pattern
– breakpoint fix for programCard
– create modifiers for existing cards to extend use (subject3up applied to subjectCardContainer makes child cards 3 up instead of 2, no-cta modifies programCardContainer so that children do not have arrow or hover affect by default)
> Punchlist layout

- src/scss/_extended.scss
- src/scss/framework/styles/_patterns.scss
– fix twoUp-gallery centering issue
> fix centering of twoUp-gallery

- src/scss/_extended.scss
– try to force padding to take affect on mobile
> Mobile home video – attempt to push the box down (works in chrome mobile view now... fingers crossed)

- public/css/vision.css
- public/vision.html
– update images urls to use content and images for vision page
> update image urls to use content and images.utk

- public/vision.html
> fix link to content for vision pdf

- public/css/vision.css
- src/scss/framework/regions/_footers.scss
- src/scss/framework/regions/_universal-footer.scss
– footer logo reduced in size
– vision footer spacing added above columns
> Footer logo

- src/scss/_extended.scss
- src/scss/components/Hero.module.scss
- src/scss/framework/styles/_blockquote.scss
– add transform back to hero dot image
– commenting out the fortysixty styles for now (not used at the moment)
> fix errors

- src/scss/_extended.scss
- src/scss/components/Hero.module.scss
- src/scss/core-blocks/_layout.scss
- src/scss/framework/regions/_universal-header.scss
- src/scss/framework/styles/_blockquote.scss
- src/scss/framework/styles/_frame.scss
This fixes several bits of invalid CSS, but I'm not sure some. The errors are straightforward, but I'm not sure what is trying to be achieved.
The first error is question is in the `_extended` partial. The error is "40% is not a flex value : 20vw 1 40%". It occurs twice, on lines 1256 and 1262.
The second is in `_Hero.module.css`. The error is "only 0 can be a length. You must put a unit after your number : translateY(500)" and it occurs on line 438.
> Fixing invalid CSS

- src/pages/index.tsx
Reduce time home page is cached to 2 min.
> refactor(home): update home page caching

- src/components/Footer.tsx
Replace break tags in footer address with paragraphs to resolve react hydration errors
> refactor(footer): remove break tags in footer address

- src/scss/core-blocks/_layout.scss
- src/scss/framework/components/_cards.scss
- src/scss/framework/components/_columns.scss
- src/scss/framework/styles/_blockquote.scss
- src/scss/framework/styles/_buttons.scss
- src/scss/framework/styles/_orange-accents.scss
- src/scss/framework/styles/_typography.scss
- src/scss/main.scss
– fix break words in columns and quote
– modify blockquote by modifying base blockquote and adding 2 modifier styles
– add tn-shape
– add outline text style for optional visit hero
> feat – fix break word, add tn-shape, quote styles

- src/components/VisitModalButton.tsx
- src/components/YoutubeCarousel.tsx
- src/scss/components/Carousel.module.scss
- src/scss/framework/styles/_modals.scss
- src/scss/framework/styles/_typography.scss
- src/scss/main.scss
– modify styles for video button overlay 
– modify styles for top buttons
– remove underline from modal header
– change CTA to fancyLink
– update modal text
> Visit page tweaks

- src/scss/components/Hero.module.scss
- src/scss/framework/components/_cover.scss
- src/scss/framework/components/_spacer.scss
- src/scss/framework/styles/_buttons.scss
- src/scss/main.scss
– fix fancyLink to allow for white link on dark
– fix visit hero card positioning
– fix fixed background to allow for alignment to right side of image to maintain subject matter
> fix links and image/card positioning

- src/components/VisitModalButton.tsx
- src/scss/framework/components/_cards.scss
- src/scss/framework/styles/_typography.scss
– fix escaping error
– fix card quote padding on mobile
– remove quotes in title of modal 
– increase h2 line-height
– tweak position of hero visit card
> tweaks to visit page

- src/scss/framework/components/_cards.scss
– padding fix for mobile hero card
– layout tweak for text next to video slider
> feat – fix the spacing of group text next to video slider

- public/meet.html
- src/components/Hero.js
- src/scss/components/Hero.module.scss
- src/scss/framework/styles/_buttons.scss
– fix meet punctuation error (backlog)
– update home hero for Q2 – new image, language, links
> Hero Update Q2-2023

- src/components/YoutubeCarousel.tsx
- src/scss/components/Carousel.module.scss
- src/scss/framework/_custom_variables.scss
- src/scss/framework/styles/_modals.scss
– add close X with animation to modals to match universal nav and search
– reduce size of video modal on med-lg screens and center
– change aspect ratio of video thumbnail in modal to 16:9
– darken overlay
> modal overlay visual tweaks

- src/components/Hero.js
Update hero language from 'Accepted' to read 'Admitted' to align with EMC
> hotfix – hero language for april 2023

- src/scss/framework/components/_cards.scss
- src/scss/framework/components/_columns.scss
- src/scss/framework/styles/_blockquote.scss
- src/scss/framework/styles/_buttons.scss
– responsive layout for card-flip
– anchor-fancy styling with animated rocky top carrot
> feat – card-flip responsive tweaks

- src/scss/framework/components/_cards.scss
- src/scss/framework/styles/_background.scss
- src/scss/framework/styles/_buttons.scss
– stat mobile considerations and breakpoints
– anchor fancy spacing and group considerations
> apply – mobile considerations

- src/scss/framework/components/_cards.scss
- src/scss/framework/styles/_typography.scss
– add tab control for card flip
– tweak quote card spacing on mobile
> Apply cleanup 01

- src/scss/framework/components/_cards.scss
> change card flip color to coolsmokey so orange hover is ada passible

- src/scss/framework/components/_cards.scss
- src/scss/framework/styles/_buttons.scss
- src/scss/framework/styles/_typography.scss
– fix responsiveness of flip cards, and repair previous bug created by ios fix
– increase leading for h4
– update padding on elements to accommodate arrows (cards, fancy links)
> Apply cleanup 02

- src/scss/framework/components/_cards.scss
- src/scss/framework/styles/_buttons.scss
- src/scss/framework/styles/_patterns.scss
– remove test border
– force breakpoints for anchor context bar
– modify pattern opacity
> fix – apply qc

- src/components/SiteSearch.tsx
- src/pages/search/[[...slug]].tsx
- src/scss/framework/_custom_variables.scss
- src/scss/framework/components/_forms.scss
- src/scss/framework/components/_pills.scss
- src/scss/framework/styles/_buttons.scss
- src/scss/pages/search.module.scss
– add tabs from utk.edu
– tweak styling of tabs (start – still working)
– change alignment of outside links
– style search input search button to match universal nav
> Search update styling

- src/components/SiteSearch.tsx
- src/scss/framework/regions/_universal-header.scss
- Resolves google search issue by reinitializing search results div on form submit. 
- Re-adds focus state style (inset box-shadow) for nav search button.
> refactor(search): resolve google search issue when visiting search page directly

- src/pages/search/[[...slug]].tsx
- src/scss/framework/styles/_typography.scss
– update h1 margins to be responsive reducing space above 'search' on mobile
> Search mobile styling

- src/middleware.ts
- src/pages/_document.tsx
- src/pages/sitemap.xml.ts
Dynamically generating sitemap and robots.txt file based on env variables to discourage search engines from indexing dev and staging sites. Also including meta robots tag with noindex, nofollow for dev/staging
> feat(sitemap): generate sitemap.xml and robots.txt

- public/css/meet.css
- public/meet.html
– update links to use prod not dev
– update intro image link
– update students on campus link
> update links to meet images 

- public/meet.html
- src/components/Hero.js
– update hero image to architecture student
– add majors back to meet page for quotes
> hero image update, add degrees back to quotes on meet

- public/css/meet.css
- public/meet.html
– add alt text to all images
– fix cover image of campus shot for ios (scale render issue)
– update text "Ready to Join Us" to "Curious About Next Steps?"
> add alt text, fix cover image of campus shot for ios, update text

- src/components/Hero.js
- src/scss/components/Hero.module.scss
- src/scss/framework/styles/_typography.scss
Fixing condensed lettering to work for a longer intro blurb
update secondary main image in hero
> hero modifications for aug 2023

- src/components/Hero.js
- src/scss/framework/styles/_patterns.scss
tweak home hero – adding slate-squeeze wrapper class to control field height of slate forms
> Flex space 2023

- src/scss/framework/styles/_patterns.scss
- src/scss/framework/styles/_typography.scss
– spacer for angle 
–fix for word-break
> tweaks to flex

- src/pages/alpha.tsx
- src/scss/pages/alpha.module.scss
refactor/restyling of alpha content to fix subtle alignment issues
> styling tweak to alignment of elements

- src/pages/vision.tsx
> add head element

- src/components/Hero.js
> write out full year

- package-lock.json
- package.json
- public/css/meet.css
- public/meet.html
- src/pages/_app.tsx
- src/pages/_document.tsx
- src/pages/social.tsx
- src/scss/components/SlateForm.module.scss
- src/scss/framework/_custom_variables.scss
- src/scss/framework/components/_pills.scss
- src/scss/framework/styles/_typography.scss
- src/scss/pages/Vision.module.scss
Implement Next.js 13 font optimization options to self-host Montserrat and Sofia fonts for improved performance
> style(fonts): replace Gotham with Montserrat and Sofia

- package-lock.json
- package.json
- public/css/meet.css
- public/meet.html
- src/components/Hero.js
- src/pages/_app.tsx
- src/pages/_document.tsx
- src/pages/social.tsx
- src/scss/components/SlateForm.module.scss
- src/scss/framework/_custom_variables.scss
- src/scss/framework/components/_pills.scss
- src/scss/framework/styles/_typography.scss
- src/scss/pages/Vision.module.scss
Updated to use Montserrat, removing Gotham.
> Gotham to Montserrat

- public/meet.html
- src/components/UniversalHeader.tsx
– remove Diversity from /meet navigation
> Development HotFix Diversity

- public/meet.html
- src/components/UniversalHeader.tsx
– remove Diversity from /meet navigation
> Staging HotFix Diversity

- public/meet.html
- update admissions links on /meet
> Admissions links

- src/components/Hero.js
Commented out for launch on Monday: 
search for "Wednesday 12/20 Launch Piece"
> remove confirm enrollment piece temporarily

- src/components/Footer.tsx
update ADA footer link to https://dae.utk.edu/eoa/ada/
> update ADA footer link

- public/meet.html
- public/vision.html
- src/components/UniversalHeader.tsx
> Hot fix 20240223

- src/components/Intro.tsx
- src/pages/academics/programs/[[...slug]].tsx
- src/scss/pages/Programs.module.scss
– refining layout for programs
> Programs update style

- src/pages/academics/programs/[[...slug]].tsx
- src/scss/pages/Programs.module.scss
- src/scss/special/forms.scss
– tweaking onlinetag
– tweaking spacing
– tweaking typography
> style refinement for programs

- src/scss/components/Intro.module.scss
- src/scss/pages/Programs.module.scss
- src/scss/special/forms.scss
– filter style tweak
– intro modification on mobile
> filter style tweak, modification to intro

- src/pages/academics/programs/[[...slug]].tsx
- src/scss/pages/Programs.module.scss
- src/scss/special/forms.scss
– language updates for program page
– style updates for filters
> refining styles

- src/scss/pages/Programs.module.scss
- src/scss/special/forms.scss
– add custom style to MuiSwitch element
> switch button styling

- src/pages/academics/programs/[[...slug]].tsx
- src/scss/pages/Programs.module.scss
- src/scss/special/forms.scss
– change style of active filter breadcrumb
– make hover visually stronger
– refine margins at small size
– add section to fix margins for 'no matching programs'
– refine leading
– degree abbreviations revert to not be uppercase
> Programs update style refinements for interaction and typography

- src/pages/academics/programs/[[...slug]].tsx
- src/scss/pages/Programs.module.scss
– tooltip for concentration
– fix for dev/prod differences in rendering search bar
– fix select title capitalization
> create tooltip, fix searchbar styling

- src/pages/academics/programs/[[...slug]].tsx
- src/pages/alpha.tsx
- src/scss/pages/Programs.module.scss
- src/scss/pages/alpha.module.scss
– fix search border radius and adornment on /programs and /alpha
– remove search button on /alpha
– cleanup unused styles
> Fix search border and adornment

- src/pages/academics/programs/[[...slug]].tsx
- src/pages/alpha.tsx
- src/scss/special/forms.scss
– fix capitalization of helper text
– remove dark blue hover select
> modify select and form helper text styling

- src/pages/academics/programs/[[...slug]].tsx
- src/scss/pages/Programs.module.scss
– add request info CTA
– language tweak to disclaimer
– tooltip letter spacing fix
> small tweak to style for infotip and disclaimer, add CTA

- src/components/Hero.js
– switch hero squareA image
– update language and links
> 2024 Q2 updates to home

- src/pages/academics/programs/[[...slug]].tsx
- src/scss/pages/Programs.module.scss
- src/scss/special/forms.scss
– add aria labels to selects
– add aria label of option to dropdown options
– change helper text to sentence case
– fix contrast for toggle
> fix qa issues

- src/components/Header.tsx
- src/pages/sitemap.xml.ts
resolve issue of subnav item not being set as current, add programs page to sitemap
> refactor(header/sitemap): fix subnav and update sitemap

- src/scss/components/Hero.module.scss
- src/scss/components/Intro.module.scss
- src/scss/framework/styles/_typography.scss
- src/scss/pages/alpha.module.scss
– change h1 color of italic font
> h1 color tweak

- src/__generated__/graphql.ts
- src/scss/framework/temp/_wds-bandaid.scss
- src/scss/main.scss
> fix spacing issues temporarily after installing Torch 1.1.2

- package-lock.json
- package.json
- src/scss/main.scss
– add new bootstrap @imports for 5.3 used by WDS 1.1.2
> Bootstrap update 5.3

- src/scss/_extended.scss
– remove added padding from campus-gallery
> fix card padding campus-gallery to compensate for wds

- src/scss/framework/components/_cards.scss
- src/scss/framework/temp/_wds-bandaid.scss
fix wds universal padding for flip card pattern alignment
> fix flip-card padding

- src/scss/framework/temp/_wds-bandaid.scss
- src/scss/main.scss
- src/scss/wds-variables/wds-manual-variables.scss
- src/scss/wds/build/components/_cards-partial.scss
– pull subject card styling
– adjust overrides for use
> Areas study 2024

- src/pages/academics/programs/[[...slug]].tsx
- broaden search for words ending in 's' (e.g. communications will match communication)
- enable multiple areas of study for programs
> refactor(programs): enable multiple aos for programs
