utkwdn/utk-atlas

- src/components/Footer.tsx
- src/components/Header.tsx
Fix Build Errors pertaining to next/link:
**./src/components/Header.tsx**
- 43:11  Warning: Do not use the HTML <a> tag to navigate to /. Use Link from 'next/link' instead. See: https://nextjs.org/docs/messages/no-html-link-for-pages  @next/next/no-html-link-for-pages
- 126:25  Warning: Do not use the HTML <a> tag to navigate to /coronavirus/. Use Link from 'next/link' instead. See: https://nextjs.org/docs/messages/no-html-link-for-pages  @next/next/no-html-link-for-pages
**./src/components/Footer.tsx**
- 70:127  Warning: Do not use the HTML <a> tag to navigate to /about/privacy/. Use Link from 'next/link' instead. See: https://nextjs.org/docs/messages/no-html-link-for-pages  @next/next/no-html-link-for-pages
> fix – build warnings for next/link in header.tsx and footer.tsx

- src/components/Footer.tsx
- src/components/Header.tsx
- src/components/Layout.tsx
- src/components/Posts.tsx
- src/components/Sprite.tsx
- src/components/TaggedPage.tsx
- src/components/calEvent.tsx
- src/middleware.ts
- src/pages/404.tsx
- src/pages/[...pageUri].tsx
- src/pages/alpha.tsx
- src/pages/category/[categorySlug]/[paginationTerm]/[categoryCursor].tsx
- src/pages/category/[categorySlug]/index.tsx
- src/pages/custom-page.tsx
- src/pages/index.tsx
- src/pages/posts/[postSlug]/[postCursor].tsx
- src/pages/posts/[postSlug]/index.tsx
- src/pages/posts/index.tsx
- src/pages/vision.js
- Fix "nested middleware" problem introduced with release of Next.js v.12.2.0
- Fix all build-blocking linting errors.
- Mostly TypeScript errors, where possibly-undefined/null values needed to be accounted for.
- Usually solved with syntax like `foo?.bar || ''` or `foo?.bar || undefined` (e.g.), which may not always be the best solution, but we can always refactor later as needed.
- In other situations, switching from `.map` to `.flatMap` was called for (to make sure that items are skipped over completely if those possibly-undefined/null values were indeed empty). If this turns out to be too aggressive here or there, can refactor later.
- Fix a couple of problems with how scripts were being imported (work here is not done, but this was needed to get the build working).
- In `alpha`, also …
> Refactor as needed to get app building again

- src/client/schema.generated.ts
- src/components/Header.tsx
- Resolve #55 
- primary and secondary navigation links are now root-relative, so using them won't take you to https://staging.cms.utk.edu/ from https://dev.cms.utk.edu/ or `localhost`
- also improve the code for the relevant parts of `Header.tsx` 
Includes an updated GQty-generated TypeScript schema file
> refactor Header to use root-relative nav-links

- package.json
- src/components/Header.tsx
Switch to React Bootstrap's `NavBar` and `OffCanvas` components for handling the main-menu's functionality.
The menu does look a little bit different now (smaller width, with the rest of the page getting a dark overlay). With some effort we could probably force it to look closer to the design-system's menu, but it might not be worth it (and to my eye it looks pretty good).
Resolves #36.
> Use React Bootstrap for functionality of main menu

- src/client/schema.generated.ts
- src/components/BlockRouter.tsx
- src/components/blocks/Accordion.tsx
- src/components/blocks/AccordionFold.tsx
- src/components/blocks/Alert.tsx
- src/components/blocks/HorizontalRule.tsx
- src/components/blocks/Lead.tsx
- src/components/blocks/Test.tsx
- src/stories/blocks/AccordionFold.stories.tsx
- src/stories/blocks/Alert.stories.tsx
- src/stories/blocks/Test.stories.tsx
- src/types/AttributesBlock.ts
- Refactor to account for Plugin update
- Fix several incorrect type-imports for block-attributes.
- Also, always use `Partial<>` for them in block-components. This makes all properties optional, which is useful because it turns out that all `attributes` declared in the block's `block.json` (in the Plugin repo) become _required_ properties, even if the corresponding `save.js` file doesn't use them at all. That would force us to include _unnecessary_ mock data in Storybook. Ideally this would be addressed by refactoring the Plugin repo so that `attributes` only include what's used in `save.js`, but making all properties optional in the React component is much easier.
- Use new `AttributesBlock` type instead of native Gutenberg `Block` type
- Allows for using `attributes` instead of …
> refactor to account for Plugin update

- package.json
- src/scss/main.scss
Pulling in base style sheets for WP core blocks into main
– Button
– Buttons
– Cover
– Columns
> Extend core

- src/components/Header.tsx
Commented out banner rather than deleting code in case banner needs to be used for a future alert.
> Remove Covid Banner

- src/pages/alpha.tsx
- Replace unnecessary `Array.prototype.find()` call with simple RegExp check in the `/alpha` page's data-reducer.
- Clean up `/alpha` code a bit.
(for #118)
> improve performance of alpha-page reducer and clean up code a bit

- package-lock.json
- package.json
- src/pages/alpha.tsx
Prototype the autocomplete/search functionality for the alpha-page (part of #118).
- Uses Material UI's [Autocomplete](https://mui.com/material-ui/react-autocomplete/) component.
- When the user selects an option from the Autocomplete list:
- in-page navigation to the corresponding item occurs (in the A-Z index below),
- and the link in that item receives focus (this is for the benefit of screen-readers).
- For now, the items displayed in the A-Z index are _not_ narrowed as the user types in the Autocomplete box. I did implement this functionality at first, but when I tried it out I did not like it, so I commented out some lines. (All the necessary code for it is still there, though, so we can easily implement it if desired. If we decide not to, then we should just remove all of it.)
- I …
> prototype autocomplete-search for alpha-page

- src/pages/vision-reactified.js
- Rename file for Reactified `/vision` page from `vision` to `vision-reactified` (to prevent name-conflict with static `/vision` endpoint that will be added).
- Set `vision-reactified` file to not actually build a page.
(for #47)
> rename reactified vision page, tell Nextjs not to build it (for #47)

- src/components/ParsedMarkup.tsx
- src/components/RequestInfoTabs.tsx
- src/components/SlateFormEmbed.tsx
- src/pages/[...pageUri].tsx
- Build `SlateFormEmbed` component.
- Build `RequestInfoTabs` component that uses the new `SlateFormEmbed` component.
- Demo the `RequestInfoTabs` component on the `/requestinfo` page.
- For now, just using a "hacky" method to include it in this page via the `ParsedMarkup` component. Before merging, the hacky method should be replaced with a more robust method (probably: on the WordPress side, leave an agreed-upon HTML comment where the `RequestInfoTabs` component should go, and use that as a flag in `ParsedMarkup` so that we can configure the parser accordingly).
> SlateFormEmbed and RequestInfoTabs

- src/pages/alpha.tsx
On `/alpha` page:
- Use `<nav>` element for alpha-links.
- Replace Autocomplete component with a normal search-input (Material UI's `TextField`).
- Make search-algorithm more restrictive so that it only matches inputs that appear verbatim (case-insensitive) in a record.
- Narrow search-results as user types in search-input.
- Wrap search-input in a form with a submit button.
- On form-submit:
- shift focus to alpha-links `<nav>` if there are search-results;
- have screen-readers announce "No results found" if there are no search-results. (Screen-readers also announce this message if the number of search-results drops to zero while the user is typing.)
> refactor alpha-page search mechanism, and make it more accessible

- src/pages/alpha.tsx
On `/alpha` page:
- enable acronyms in search
- make alpha-nav's aria-label more concise
> enable acronyms in alpha-search, and tweak alpha-nav aria-label

- public/ittakesavolunteer.html
Fix the form at the bottom of the static `/ittakesavolunteer` page.
> fix it-takes-a-volunteer Slate form embed

- src/client/schema.generated.ts
These errors will still need to be resolved the next time the schema is updated.
> Rolled back schema.generated.ts to resolve build errors caused by updated typescript types.

- src/pages/alpha.tsx
- src/scss/pages/alpha.module.scss
– fix mobile breakpoints by allowing url string to wrap (this was breaking the alignment)
– add sticky letters back to mobile with reduced size alphabet
– fix height of search letters at mobile to allow sticky to snug to bottom no matter what search term
– fix alignment of result letters at mid size
– reduce result letter size at various breakpoints
– other minor style tweaks to tighten the appearance as a whole
> Punchlist alpha

- src/components/Footer.tsx
- src/scss/framework/components/_forms.scss
- The social media links had a blue hover, this was due to them have `.btn` classes, which are now removed.
- The Instagram icon was wildly misaligned, this was due to it not have proper `width` and `height` attributes.
- Extended the bootstrap `form` classes to make it look nicer. Some of slate's embedded styles still present cause minor misalignments, but in much better shape now.
> Request style

- src/components/PageTitle.tsx
- src/scss/framework/styles/_orange_mark.scss
- Reconfigured "orange mark" style to be `::after` instead of `::before`. The style is found at `src/scss/framework/styles/_orange_mark`
- Added the `.orange_marke` class to the default page title. (File in `src/components/PageTitle.tsx`)
> Adding orange hash to the page title headlines

- src/scss/core-blocks/_layout.scss
- src/scss/framework/components/_cards.scss
- src/scss/framework/components/_spacer.scss
- src/scss/framework/styles/_buttons.scss
- src/scss/framework/styles/_fixes.scss
- src/scss/framework/styles/_frame.scss
- src/scss/framework/styles/_patterns.scss
- src/scss/main.scss
fix twoUp-Gallery responsiveness (small/large full width off-center image gallery pattern)
– adjust spacing with css after removing WP spacer block from pattern 
– add controls for small and large images to better control vertical spacing
– fix pattern not centering properly at certain sizes
– tweak alignment of small image on mobile to have better pattern flow on smaller devices
Adjust card h2 and h3
– increase card headers sizing on mobile by increasing the multiplier to keep headers from being smaller than body
Fixes for render errors on certain older iPad and Iphone iOS versions
– fix render issues on older browsers not supporting flex gap (row and columns) by replacing with margins on specific devices
– fix orange frame (drop-shadow) inconsistent render by forcing gpu render of …
> Responsive cleanup

- src/scss/_extended.scss
- src/scss/components/SlateForm.module.scss
- src/scss/framework/_custom_variables.scss
- src/scss/framework/components/_forms.scss
Restyle forms
– add text marking optional fields
– add inline text error message marking required fields (only appear if fields were not filled in before submit)
– change layout of label and fields to stack
– add ADA color of deep pink for alerts messaging
– modify slate error dialog to use new alert color
– fix input fields alignment
– update SlateForm.module to use common styles
> Restyle slate forms

- src/components/SlateModalTabs.tsx
- src/scss/components/SlateForm.module.scss
- src/scss/framework/styles/_fixes.scss
Resolves display issues when adding slate modal tabs inside div with framedOrangeShadow class. This and potentially other classes with css transforms prevent position: fixed modal from overlaying the entire page.
> fix(slate): update styles to resolve slate display issues

- src/components/SiteSearch.tsx
- src/components/UniversalHeader.tsx
- src/pages/search/[[...slug]].tsx
- src/scss/framework/_custom_variables.scss
- src/scss/framework/components/_pills.scss
- src/scss/framework/regions/_search_area.scss
- src/scss/framework/styles/_buttons.scss
- src/scss/pages/search.module.scss
– tab style influenced by button corners
– add emphasis state with active tab slightly larger than inactive tabs to aid in visible difference
– modify mobile breakpoints 
– search button style unified across input and overlay uses, with mobile short version
– modify width of search in page
– add helper text above search box to mobile widths due to tabs turning into buttons and visual disconnect between UI elements
– adjust overlay for use on smaller screens
> Search style – search button, tab/pills, mobile

- src/scss/components/Carousel.module.scss
– Increase contrast ratio of slider buttons due to lack of ADA orange by switching to smokey
– Increase the size of buttons on mobile for easier use
> tweak colors and size of visit slider for accessibility

- src/scss/framework/components/_pills.scss
– reduce x padding slighting in active tab
– reduce margin between tabs slightly
– remove last-childs margin to give more space
– add fallback button styling for the smallest of small screens that remains consistent with tab feel
> tweak smallest screens for iphone 13 mini 

- src/scss/framework/styles/_patterns.scss
– add a class to force media-text block using 33% width to break earlier at medium widths
> fix medium breakpoint for media-text utilizing third of space

- src/scss/framework/components/_cards.scss
- src/scss/framework/components/_cover.scss
– add vertical scale to cover image to fix WordPress lack of responsiveness for height at mobile sizes
– add style to increase height of image behind text box
> mobile tweaks for cover images
